# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 18:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrushTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.CharField(max_length=500, verbose_name='产品链接')),
                ('store_ww', models.CharField(max_length=50, verbose_name='店铺旺旺')),
                ('store_name', models.CharField(max_length=50, verbose_name='店铺名称')),
                ('single_price', models.FloatField(default=0, verbose_name='单次价格')),
                ('numbers', models.IntegerField(default=0, verbose_name='刷单次数')),
                ('is_consulting_service', models.BooleanField(verbose_name='是否咨询客服')),
                ('activity_sKU', models.CharField(max_length=100, verbose_name='活动SKU选项')),
                ('order_message', models.CharField(max_length=100, verbose_name='网店订单留言')),
                ('added_message', models.CharField(max_length=500, verbose_name='补充说明')),
                ('title', models.CharField(max_length=300, verbose_name='活动标题')),
                ('client_type', models.CharField(max_length=50, verbose_name='客户端类型')),
                ('image', models.ImageField(upload_to='activity_image', verbose_name='活动图片')),
                ('activity_platform', models.CharField(max_length=100, verbose_name='活动平台')),
                ('activity_entrance', models.CharField(max_length=100, verbose_name='活动入口')),
                ('activity_keyword', models.CharField(max_length=100, verbose_name='进店关键字')),
                ('search_rank', models.CharField(max_length=100, verbose_name='搜索排序')),
                ('price_highest', models.FloatField(verbose_name='最高价格')),
                ('price_minimum', models.FloatField(verbose_name='最高价格')),
                ('delivery_place', models.CharField(max_length=100, verbose_name='发货地')),
                ('style', models.CharField(max_length=100, verbose_name='款式')),
                ('before_activity', models.CharField(max_length=100, verbose_name='活动前')),
                ('order_payment_time', models.CharField(max_length=100, verbose_name='下单付款时间')),
                ('allow_pay', models.CharField(max_length=200, verbose_name='允许付款方式（用逗号隔开）')),
                ('evaluation', models.CharField(max_length=200, verbose_name='产品自评')),
                ('is_photo', models.BooleanField(default=False, verbose_name='是否实拍')),
                ('message_type', models.IntegerField(choices=[(1, '不限'), (2, '男'), (3, '女')], default=1, help_text='买家性别: 1(不限),2(男),3(女)', verbose_name='买家性别')),
                ('activity_interval', models.CharField(max_length=200, verbose_name='活动间隔')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='刷单任务发布者')),
            ],
        ),
    ]
