# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brushtask',
            old_name='activity_sKU',
            new_name='activity_sku',
        ),
        migrations.AddField(
            model_name='brushtask',
            name='state',
            field=models.BooleanField(default=True, verbose_name='活动状态'),
        ),
    ]
