# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 10:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_auto_20190313_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_price', models.FloatField(default=0, verbose_name='本金')),
                ('commission', models.FloatField(default=0, verbose_name='佣金')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='接单时间')),
                ('state_type', models.IntegerField(choices=[(1, '已接单'), (2, '审核中'), (3, '已确认')], default=1, help_text='买家性别: 1(已接单),2(审核中),3(已确认)', verbose_name='任务状态')),
                ('buyer', models.CharField(default='', max_length=100, verbose_name='买家')),
                ('order', models.CharField(default='', max_length=100, verbose_name='订单号')),
                ('Courier', models.CharField(default='', max_length=100, verbose_name='快递')),
                ('Courier_number', models.CharField(default='', max_length=100, verbose_name='快递单号')),
            ],
        ),
        migrations.AlterField(
            model_name='brushtask',
            name='single_price',
            field=models.FloatField(default=0, max_length=600, verbose_name='本金'),
        ),
        migrations.AddField(
            model_name='orderinfos',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.BrushTask', verbose_name='所接任务'),
        ),
        migrations.AddField(
            model_name='orderinfos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接单人'),
        ),
    ]
