# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190313_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfos',
            options={'verbose_name': '接单订单', 'verbose_name_plural': '接单订单'},
        ),
        migrations.AlterField(
            model_name='brushtask',
            name='image',
            field=models.ImageField(blank=True, upload_to='activity_image', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='orderinfos',
            name='Courier',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='快递'),
        ),
        migrations.AlterField(
            model_name='orderinfos',
            name='Courier_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='快递单号'),
        ),
        migrations.AlterField(
            model_name='orderinfos',
            name='buyer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='买家'),
        ),
        migrations.AlterField(
            model_name='orderinfos',
            name='order',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfos',
            name='state_type',
            field=models.IntegerField(choices=[(1, '已接单'), (2, '审核中'), (3, '已确认')], default=1, help_text='订单状态: 1(已接单),2(审核中),3(已确认)', verbose_name='订单状态'),
        ),
    ]
