# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190313_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfos',
            name='activity_name',
            field=models.CharField(default='', max_length=500, verbose_name='活动名称'),
        ),
    ]
