# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 14:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0006_orderinfos_activity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_name', models.CharField(default='', max_length=100, verbose_name='收货人')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='收货人电话')),
                ('province', models.CharField(default='', max_length=100, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=100, verbose_name='城市')),
                ('district', models.CharField(default='', max_length=100, verbose_name='区域')),
                ('address', models.CharField(default='', max_length=100, verbose_name='详细地址')),
                ('postal_code', models.CharField(default='', max_length=6, verbose_name='邮编')),
                ('state', models.BooleanField(default=False, verbose_name='任务状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布者')),
            ],
            options={
                'verbose_name': '物流任务',
                'verbose_name_plural': '物流任务',
            },
        ),
        migrations.CreateModel(
            name='LogisticsTaskOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False, verbose_name='任务状态')),
                ('Courier_number', models.CharField(blank=True, default='', max_length=100, verbose_name='快递单号')),
                ('content', models.TextField(default='', help_text='物流信息', verbose_name='物流信息')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.LogisticsTask', verbose_name='所接物流任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接受任务者')),
            ],
        ),
    ]
