# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_logisticstask_logisticstaskorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticstaskorder',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
