# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_logisticstaskorder_add_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logisticstaskorder',
            options={'verbose_name': '物流任务订单', 'verbose_name_plural': '物流任务订单'},
        ),
        migrations.AddField(
            model_name='logisticstask',
            name='commission',
            field=models.FloatField(default=0, verbose_name='佣金'),
        ),
        migrations.AddField(
            model_name='logisticstaskorder',
            name='commission',
            field=models.FloatField(default=0, verbose_name='佣金'),
        ),
        migrations.AlterField(
            model_name='logisticstask',
            name='state',
            field=models.BooleanField(default=False, verbose_name='任务被接状态'),
        ),
    ]
