# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20190319_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticstaskorder',
            name='content',
            field=models.TextField(blank=True, default='', help_text='物流信息', verbose_name='物流信息'),
        ),
    ]
