# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20190319_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticstaskorder',
            name='mobile',
            field=models.CharField(default='', max_length=11, verbose_name='收货人电话'),
        ),
        migrations.AddField(
            model_name='logisticstaskorder',
            name='receive_name',
            field=models.CharField(default='', max_length=100, verbose_name='收货人'),
        ),
    ]
