# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20190320_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticstask',
            name='state',
            field=models.IntegerField(choices=[(1, '等待完成'), (2, '已取消'), (3, '已完成')], default=1, help_text='任务状态: 1(等待完成),2(已取消),3(已完成)', verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='logisticstaskorder',
            name='state',
            field=models.BooleanField(default=False, help_text='任务状态', verbose_name='任务状态'),
        ),
    ]
