# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20190320_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticstask',
            name='state',
            field=models.IntegerField(choices=[(0, '等待完成'), (1, '已取消'), (2, '已完成')], default=0, help_text='任务状态: 0(等待完成),1(已取消),2(已完成)', verbose_name='任务状态'),
        ),
    ]
