# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(default='store_image/default', upload_to='store_image', verbose_name='卖家中心图片'),
        ),
    ]
