# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Be_Invite_code',
            field=models.CharField(default='', max_length=8, verbose_name='被邀请码'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Invite_code',
            field=models.CharField(default='', max_length=8, verbose_name='个人邀请码'),
        ),
    ]
