# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190313_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Be_Invite_code',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='被邀请码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Invite_code',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='个人邀请码'),
        ),
    ]
