# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 14:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190318_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargeorder',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='rechargeorder',
            name='arrival_money',
            field=models.FloatField(default=0, help_text='到账金额', verbose_name='到账金额'),
        ),
        migrations.AlterField(
            model_name='rechargeorder',
            name='money',
            field=models.FloatField(help_text='充值金额', verbose_name='充值金额'),
        ),
        migrations.AlterField(
            model_name='rechargeorder',
            name='order_number',
            field=models.CharField(blank=True, help_text='充值单号', max_length=300, null=True, verbose_name='充值单号'),
        ),
        migrations.AlterField(
            model_name='rechargeorder',
            name='state',
            field=models.BooleanField(default=False, help_text='审核状态 false代表审核中 true代表审核完成', verbose_name='处理状态'),
        ),
        migrations.AlterField(
            model_name='rechargeorder',
            name='user',
            field=models.ForeignKey(help_text='充值用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='充值用户'),
        ),
        migrations.AlterField(
            model_name='store',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default='', help_text='详细地址', max_length=100, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(default='', help_text='城市', max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='store',
            name='district',
            field=models.CharField(default='', help_text='区域', max_length=100, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, default='store_image/default', help_text='卖家中心图片', null=True, upload_to='store_image', verbose_name='卖家中心图片'),
        ),
        migrations.AlterField(
            model_name='store',
            name='mobile',
            field=models.CharField(default='', help_text='电话', max_length=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='store',
            name='postal_code',
            field=models.CharField(default='', help_text='邮编', max_length=6, verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='store',
            name='province',
            field=models.CharField(default='', help_text='省份', max_length=100, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='store',
            name='sender_name',
            field=models.CharField(default='', help_text='发件人', max_length=100, verbose_name='发件人'),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.BooleanField(default=False, help_text='审核状态', verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_category',
            field=models.CharField(default='', help_text='店铺类目', max_length=100, verbose_name='店铺类目'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='', help_text='店铺名称', max_length=100, verbose_name='店铺名称'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_url',
            field=models.URLField(help_text='店铺链接', max_length=500, verbose_name='店铺链接'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_ww',
            field=models.CharField(default='', help_text='店铺旺旺', max_length=100, verbose_name='店铺旺旺'),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Be_Invite_code',
            field=models.CharField(blank=True, default='', help_text='被邀请人的邀请码', max_length=8, verbose_name='被邀请码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Invite_code',
            field=models.CharField(blank=True, default='', help_text='个人邀请码 用来给别人填 代表是被次账号邀请', max_length=8, verbose_name='个人邀请码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=0, help_text='余额', null=True, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='出生年月', null=True, verbose_name='出生年月'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', help_text='性别', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='电话', max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, help_text='姓名', max_length=30, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qq_number',
            field=models.CharField(blank=True, help_text='qq号码', max_length=15, null=True, verbose_name='QQ号码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(choices=[(0, '管理员'), (1, '卖家'), (2, '刷手'), (3, '代理')], default=1, help_text='账号类别: 0(管理员),1(卖家),2(刷手),3(代理)', verbose_name='账号类别'),
        ),
        migrations.AlterField(
            model_name='withdraworder',
            name='Bank_number',
            field=models.CharField(blank=True, help_text='提现银行卡号', max_length=50, null=True, verbose_name='提现银行卡号'),
        ),
        migrations.AlterField(
            model_name='withdraworder',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='withdraworder',
            name='arrival_money',
            field=models.FloatField(default=0, help_text='到账金额', verbose_name='到账金额'),
        ),
        migrations.AlterField(
            model_name='withdraworder',
            name='money',
            field=models.FloatField(help_text='提现金额', verbose_name='提现金额'),
        ),
        migrations.AlterField(
            model_name='withdraworder',
            name='name',
            field=models.CharField(default='', help_text='银行卡持有人姓名', max_length=6, verbose_name='银行卡持有人姓名'),
        ),
        migrations.AlterField(
            model_name='withdraworder',
            name='state',
            field=models.BooleanField(default=False, help_text='处理状态', verbose_name='处理状态'),
        ),
        migrations.AlterField(
            model_name='withdraworder',
            name='user',
            field=models.ForeignKey(help_text='提现用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提现用户'),
        ),
    ]
